package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/djspinmonkey/lightgraph-go/graph/model"
)

// DoSomething is a sample resolver for a mutation.
func (r *mutationResolver) DoSomething(ctx context.Context, task string) (string, error) {
	// Totally do the thing.
	return fmt.Sprintf("It is technically possible that I may have done this thing: %s", task), nil
}

// Actor is the resolver for the actor field.
func (r *queryResolver) Actor(ctx context.Context) (*model.Actor, error) {
	return &model.Actor{}, nil
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, id string) (*model.Organization, error) {
	return &model.Organization{ID: id, Name: id}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
